### ISSUE TITLE
NullPointerException Error when trying to generate PDG/CPG from cpg.bin

### ISSUE THREAD

**Issue by jsanket9578** [plume-oss/plume#163]
Upon running the OverflowDbApp in sample project (with the provided sample java file as input) and using joern-export to generate PDG or CPG14, a NullPointerException Error is thrown, trace below. 

Note:
1. AST and CFG get created without any problems. 
2. The exact same behaviour was observed when I earlier tried doing this using Joern directly (via joern-parse command). 

```java
Exception in thread "main" java.lang.NullPointerException
	at io.shiftleft.semanticcpg.dotgenerator.DotSerializer$.escape(DotSerializer.scala:86)
	at io.shiftleft.semanticcpg.dotgenerator.DotSerializer$.edgeToDot(DotSerializer.scala:77)
	at io.shiftleft.semanticcpg.dotgenerator.DotSerializer$.$anonfun$dotGraph$2(DotSerializer.scala:25)
	at scala.collection.immutable.List.map(List.scala:250)
	at io.shiftleft.semanticcpg.dotgenerator.DotSerializer$.dotGraph(DotSerializer.scala:25)
	at io.shiftleft.dataflowengineoss.dotgenerator.DotCpg14Generator$.dotGraphForMethod(DotCpg14Generator.scala:18)
	at io.shiftleft.dataflowengineoss.dotgenerator.DotCpg14Generator$.$anonfun$toDotCpg14$1(DotCpg14Generator.scala:11)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:575)
	at scala.collection.IterableOps.head(Iterable.scala:218)
	at scala.collection.IterableOps.head$(Iterable.scala:218)
	at overflowdb.traversal.Traversal.head(Traversal.scala:17)
	at io.shiftleft.dataflowengineoss.layers.dataflows.DumpCpg14.$anonfun$create$1(DumpCpg14.scala:30)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at overflowdb.traversal.Traversal.foreach(Traversal.scala:17)
	at io.shiftleft.dataflowengineoss.layers.dataflows.DumpCpg14.create(DumpCpg14.scala:28)
	at io.shiftleft.joern.JoernExport$.$anonfun$new$4(JoernExport.scala:87)
	at io.shiftleft.joern.JoernExport$.$anonfun$new$4$adapted(JoernExport.scala:58)
	at scala.Option.foreach(Option.scala:437)
	at io.shiftleft.joern.JoernExport$.delayedEndpoint$io$shiftleft$joern$JoernExport$1(JoernExport.scala:58)
	at io.shiftleft.joern.JoernExport$delayedInit$body.apply(JoernExport.scala:31)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at io.shiftleft.joern.JoernExport$.main(JoernExport.scala:31)
	at io.shiftleft.joern.JoernExport.main(JoernExport.scala)
```

**Comment by DavidBakerEffendi** [comment]
Thanks for reporting this - will have a look into it

**Comment by jsanket9578** [comment]
> Thanks for reporting this - will have a look into it

Sure. Just to add, AST and CFG work perfectly fine, it's only the PDG/DDG that is problematic.

**Comment by DavidBakerEffendi** [comment]
Okay so perhaps my unrelated bugfix which is present in v0.4.4 fixed this issue (I have a hunch of what it was, but anyways) as I used the CPG from `OverflowDbApp` using Plume v0.4.4 and used `joern-parse` then `joern-export` which did not throw any issue for the `pdg`, `ddg`, nor `cpg14` runs.

Please confirm if everything is now alright on your side - I did not look at the exports themselves to validate anything yet but at least no exceptions are happening.

**Comment by DavidBakerEffendi** [comment]
Confirmed the issue is still present - seems as though the DotGenerator runs into a null edge label when writing to the dot file

**Comment by DavidBakerEffendi** [comment]
This PR will fix the symptom but not the issue, will investigate what is missing on Plume's side: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1186

**Comment by popthink** [comment]
Perhaps, this message could be related with this issue.
You can reproduce it with CdgPass in joern.
```
 WARN CdgPass: Found CDG edge starting at METHOD node. This is most likely caused by an invalid CFG. Method:[]number of outgoing CFG edges from METHOD node: 2
```
