### ISSUE TITLE
RuntimeException When Running an Update

### ISSUE THREAD

**Issue by DavidBakerEffendi** [plume-oss/plume#178]
**Describe the bug and, if possible, what you should expect**
While running an updating on `apache/tinkerpop/gremlin-driver`.

**To Reproduce**
1. Go to `plume-benchmarks` repo
2. Enable `run-updates` and `apache/tinkerpop/gremlin-driver`
3. Run with `OverflowDbDriver`
4. See error on first update on the `Building 142 method bodies`

**Screenshots and/or Stacktraces**
```
[ERROR] 2021-04-13 16:44:32.084 [main] OverflowDbDriver - Edge of type AST with direction OUT not supported by class IdentifierDb
java.lang.RuntimeException: Edge of type AST with direction OUT not supported by class IdentifierDb
	at overflowdb.NodeDb.storeAdjacentNode(NodeDb.java:621) ~[overflowdb-core-1.30.jar:1.30]
	at overflowdb.NodeDb.storeAdjacentNode(NodeDb.java:602) ~[overflowdb-core-1.30.jar:1.30]
	at overflowdb.NodeDb.addEdge(NodeDb.java:298) ~[overflowdb-core-1.30.jar:1.30]
	at overflowdb.NodeRef.addEdge(NodeRef.java:151) ~[overflowdb-core-1.30.jar:1.30]
	at io.github.plume.oss.drivers.OverflowDbDriver.createEdge(OverflowDbDriver.kt:154) ~[plume-0.4.5.jar:0.4.5]
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Java: OpenJDK 11
 - Plume Version 0.4.5 (also happens in 0.4.4)

**Comment by DavidBakerEffendi** [comment]
Further investigation shows that this may be related to saving and reconnecting call edges
