### ISSUE TITLE
Classic ID Resolution Bug

### ISSUE THREAD

**Issue by DavidBakerEffendi** [plume-oss/plume#210]
**Describe the bug and, if possible, what you should expect**
A bug where ID's are mismatched on target and in-memory OverflowDB nodes is back. Perhaps this is associated with the cache system?

**To Reproduce**
1. Launch benchmark suite with "spring-boot" or "scribejava" enabled
2. Run update benchark
3. View the below exception thrown during data-flow pass

**Screenshots and/or Stacktraces**
```
ERROR] 2021-09-24 12:06:38.724 [scala-execution-context-global-91] DeltaGraph - Exception while adding edge between NewMethodBuilder(11336) (io.shiftleft.codepropertygraph.generated.nodes.Type[label=TYPE; id=11336]) and NewIdentifierBuilder(274909) (io.shiftleft.codepropertygraph.generated.nodes.Identifier[label=IDENTIFIER; id=274909])
java.lang.RuntimeException: Edge with type='CONTAINS' with direction='OUT' not supported by nodeType='TYPE'
        at overflowdb.NodeDb.storeAdjacentNode(NodeDb.java:637) ~[overflowdb-core-1.61.jar:1.61]
        at overflowdb.NodeDb.storeAdjacentNode(NodeDb.java:616) ~[overflowdb-core-1.61.jar:1.61]
        at overflowdb.NodeDb.addEdge(NodeDb.java:303) ~[overflowdb-core-1.61.jar:1.61]
        at overflowdb.NodeRef.addEdge(NodeRef.java:161) ~[overflowdb-core-1.61.jar:1.61]
        at io.github.plume.oss.domain.model.DeltaGraph$toOverflowDb$2.invoke(DeltaGraph.kt:62) ~[plume-0.5.14.jar:0.5.14]
        at io.github.plume.oss.domain.model.DeltaGraph.toOverflowDb(DeltaGraph.kt:75) ~[plume-0.5.14.jar:0.5.14]
        at io.github.plume.oss.passes.DataFlowPass$runPass$1$2.invokeSuspend(DataFlowPass.kt:59) ~[plume-0.5.14.jar:0.5.14]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.4.21.jar:1.4.21-release-351 (1.4.21)]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:?]
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:?]
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:?]
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:?]
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:?]
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:?]
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:?]
        at io.github.plume.oss.passes.DataFlowPass.runPass(DataFlowPass.kt:52) ~[plume-0.5.14.jar:0.5.14]
        at io.github.plume.oss.Extractor$project$20.invoke(Extractor.kt:347) ~[plume-0.5.14.jar:?]
        at io.github.plume.oss.Extractor$project$20.invoke(Extractor.kt:88) ~[plume-0.5.14.jar:?]
        at io.github.plume.oss.metrics.PlumeTimer.measureFunctionTime(PlumeTimer.kt:32) ~[plume-0.5.14.jar:0.5.14]
        at io.github.plume.oss.metrics.PlumeTimer.measure(PlumeTimer.kt:43) ~[plume-0.5.14.jar:0.5.14]
        at io.github.plume.oss.Extractor.project(Extractor.kt:347) ~[plume-0.5.14.jar:?]
        at io.github.plume.oss.Extractor.project$default(Extractor.kt:188) ~[plume-0.5.14.jar:?]
        at io.github.plume.oss.Extractor.project(Extractor.kt) ~[plume-0.5.14.jar:?]
        at io.github.plume.oss.Main$.runBenchmark(Main.scala:182) ~[classes/:?]
        at io.github.plume.oss.RunBenchmark$.runInitBuild(RunBenchmark.scala:62) ~[classes/:?]
        at io.github.plume.oss.RunBenchmark$.$anonfun$runBuildAndStore$1(RunBenchmark.scala:47) ~[classes/:?]
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Java: AdoptOpenJDK 11
 - Plume Version 0.6.1 and others such as 0.5.14

**Comment by DavidBakerEffendi** [comment]
Benchmark suite was not cleaning up properly after one of the experiments.
