### ISSUE TITLE
Soot crash on jar analysis

### ISSUE THREAD

**Issue by itsacoderepo** [plume-oss/plume#57]
After importing [stellar-common-0.7.2.zip](https://github.com/plume-oss/plume/files/5947120/stellar-common-0.7.2.zip) (replace `.zip` with `.jar`) in joern (`importCode("stellar-common-0.7.2.jar")`), i get the following crash:

```
/tmp/stellar-common-0.7.2.jar7549663979722689849/META-INF/annotations/org.apache.metron.stellar.dsl.Stellar
/tmp/stellar-common-0.7.2.jar7549663979722689849/META-INF/MANIFEST.MF
Creating CPG for directory: /tmp/stellar-common-0.7.2.jar7549663979722689849
java.lang.RuntimeException: No method source set for method <java.lang.Object: int hashCode()>
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:398)
	at io.github.plume.oss.Extractor$project$graphs$5.apply(Extractor.kt:254)
	at io.github.plume.oss.Extractor$project$graphs$5.apply(Extractor.kt:64)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at kotlin.streams.jdk8.StreamsKt.toList(Streams.kt:72)
	at io.github.plume.oss.Extractor.project(Extractor.kt:254)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.$anonfun$createCpgForDirectory$2(PlumeCpgGenerator.scala:41)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.$anonfun$createCpgForDirectory$2$adapted(PlumeCpgGenerator.scala:36)
	at scala.util.Using$.$anonfun$apply$1(Using.scala:261)
	at scala.util.Using$.apply(Using.scala:113)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.createCpgForDirectory(PlumeCpgGenerator.scala:36)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.createCpgForArchive(PlumeCpgGenerator.scala:52)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.$anonfun$createCpgForJava$4(PlumeCpgGenerator.scala:23)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:168)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.createCpgForJava(PlumeCpgGenerator.scala:18)
	at io.shiftleft.joern.JoernParse$.generateCpg(JoernParse.scala:25)
	at io.shiftleft.joern.JoernParse$.$anonfun$new$1(JoernParse.scala:12)
	at io.shiftleft.joern.JoernParse$.$anonfun$new$1$adapted(JoernParse.scala:10)
	at scala.Option.foreach(Option.scala:437)
	at io.shiftleft.joern.JoernParse$.delayedEndpoint$io$shiftleft$joern$JoernParse$1(JoernParse.scala:10)
	at io.shiftleft.joern.JoernParse$delayedInit$body.apply(JoernParse.scala:7)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at io.shiftleft.joern.JoernParse$.main(JoernParse.scala:7)
	at io.shiftleft.joern.JoernParse.main(JoernParse.scala)
moving cpg.bin.zip to cpg.bin because it is already a database file
Creating working copy of CPG to be safe
Loading base CPG from: /home/foo/bar/joern/workspace/stellar-common-0.7.2.jar/cpg.bin.tmp
Adding default overlays to base CPG
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
Code successfully imported. You can now query it using `cpg`.
For an overview of all imported code, type `workspace`.
res1: Option[Cpg] = Some(value = io.shiftleft.codepropertygraph.Cpg@441fd20d)
```

**Comment by fabsx00** [comment]
Given that plume translates one class file at a time, maybe installing an exception handler to skip class files that result in soot exceptions is a good way to go.
