### ISSUE TITLE
ZipException - invalid CEN header

### ISSUE THREAD

**Issue by itsacoderepo** [plume-oss/plume#58]
After importing the file [metron-statistics-0.7.2.zip](https://github.com/plume-oss/plume/files/5947152/metron-statistics-0.7.2.zip) (replace `.zip` with `.jar`) in joern, i see the following crash:

```
joern> importCode("metron-statistics-0.7.2.jar") 
Using generator for language: JAVA
Creating project `metron-statistics-0.7.2.jar` for code at `metron-statistics-0.7.2.jar`
Project with name metron-statistics-0.7.2.jar already exists - overwriting
Archive detected. Extracting.
java.util.zip.ZipException: invalid CEN header (bad entry name)
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1581)
	at java.base/java.util.zip.ZipFile$Source.checkEncoding(ZipFile.java:1357)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1550)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1288)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1251)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:732)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:849)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:300)
	at better.files.File.unzipTo(File.scala:1242)
	at better.files.File.unzip(File.scala:1328)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.createCpgForArchive(PlumeCpgGenerator.scala:50)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.$anonfun$createCpgForJava$4(PlumeCpgGenerator.scala:23)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:168)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.createCpgForJava(PlumeCpgGenerator.scala:18)
	at io.shiftleft.joern.JoernParse$.generateCpg(JoernParse.scala:25)
	at io.shiftleft.joern.JoernParse$.$anonfun$new$1(JoernParse.scala:12)
	at io.shiftleft.joern.JoernParse$.$anonfun$new$1$adapted(JoernParse.scala:10)
	at scala.Option.foreach(Option.scala:437)
	at io.shiftleft.joern.JoernParse$.delayedEndpoint$io$shiftleft$joern$JoernParse$1(JoernParse.scala:10)
	at io.shiftleft.joern.JoernParse$delayedInit$body.apply(JoernParse.scala:7)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at io.shiftleft.joern.JoernParse$.main(JoernParse.scala:7)
	at io.shiftleft.joern.JoernParse.main(JoernParse.scala)
java.nio.file.NoSuchFileException: /home/foo/bar/joern/workspace/metron-statistics-0.7.2.jar/cpg.bin.zip
  sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
  sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
  sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
  sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
  java.nio.file.Files.newByteChannel(Files.java:371)
  java.nio.file.Files.newByteChannel(Files.java:422)
  java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
  java.nio.file.Files.newInputStream(Files.java:156)
  better.files.File.newInputStream(File.scala:455)
  better.files.File.bytes(File.scala:239)
  io.shiftleft.console.cpgcreation.CpgGeneratorFactory.isZipFile(CpgGeneratorFactory.scala:85)
  io.shiftleft.console.cpgcreation.CpgGeneratorFactory.$anonfun$runGenerator$2(CpgGeneratorFactory.scala:60)
  scala.Option.map(Option.scala:242)
  io.shiftleft.console.cpgcreation.CpgGeneratorFactory.runGenerator(CpgGeneratorFactory.scala:58)
  io.shiftleft.console.cpgcreation.ImportCode.$anonfun$apply$7(ImportCode.scala:130)
  scala.Option.flatMap(Option.scala:283)
  io.shiftleft.console.cpgcreation.ImportCode.$anonfun$apply$6(ImportCode.scala:124)
  scala.Option.flatMap(Option.scala:283)
  io.shiftleft.console.cpgcreation.ImportCode.io$shiftleft$console$cpgcreation$ImportCode$$apply(ImportCode.scala:123)
  io.shiftleft.console.cpgcreation.ImportCode.$anonfun$apply$2(ImportCode.scala:44)
  scala.Option.flatMap(Option.scala:283)
  io.shiftleft.console.cpgcreation.ImportCode.apply(ImportCode.scala:43)
  ammonite.$sess.cmd7$.<clinit>(cmd7.sc:1)
```

**Comment by DavidBakerEffendi** [comment]
This seems to be a Joern issue as no Plume classes are being hit in this stacktrace. @fabsx00 do you have an idea of what's happening? My guess is something to do with the `.jar` suffix of the project name.

**Comment by fabsx00** [comment]
I'm seeing similar issues when using Java 11. I'm looking into it.

**Comment by itsacoderepo** [comment]
Closing, because it is not plume related.

**Comment by DavidBakerEffendi** [comment]
> Closing, because it is not plume related.

I've made Plume accept and process JARs internally now using Java's builtin`ZipEntry` library. Sent my PR for this to Joern and hopefully this will solve itself.
