### ISSUE TITLE
Crash on importing jar file

### ISSUE THREAD

**Issue by itsacoderepo** [plume-oss/plume#69]
Steps to reproduce:
1. wget https://github.com/OpenRefine/OpenRefine/releases/download/3.4.1/openrefine-linux-3.4.1.tar.gz 
2. tar xvf openrefine-linux-3.4.1.tar.gz
3. jar  -cvf openrefine.jar openrefine-3.4.1/
4. Import jar in joern:
```
joern> importCode("openrefine.jar") 
Using generator for language: JAVA
Creating project `openrefine.jar` for code at `openrefine.jar`
Creating CPG for: openrefine.jar
Exception in thread "main" java.lang.NoSuchMethodError: 'io.shiftleft.codepropertygraph.generated.nodes.NewTypeDeclBuilder io.shiftleft.codepropertygraph.generated.nodes.NewTypeDeclBuilder.fullname(java.lang.String)'
	at io.github.plume.oss.util.SootToPlumeUtil.buildTypeDeclaration(SootToPlumeUtil.kt:343)
	at io.github.plume.oss.util.SootToPlumeUtil.buildTypeDeclaration$default(SootToPlumeUtil.kt:327)
	at io.github.plume.oss.Extractor$createExternalTypes$3.invoke(Extractor.kt:322)
	at io.github.plume.oss.Extractor$createExternalTypes$3.invoke(Extractor.kt:73)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at io.github.plume.oss.Extractor.createExternalTypes(Extractor.kt:578)
	at io.github.plume.oss.Extractor.project(Extractor.kt:290)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.$anonfun$createCpgForInputPath$2(PlumeCpgGenerator.scala:39)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.$anonfun$createCpgForInputPath$2$adapted(PlumeCpgGenerator.scala:34)
	at scala.util.Using$.$anonfun$apply$1(Using.scala:261)
	at scala.util.Using$.apply(Using.scala:113)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.createCpgForInputPath(PlumeCpgGenerator.scala:34)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.$anonfun$createCpgForJava$4(PlumeCpgGenerator.scala:21)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:168)
	at io.shiftleft.joern.plume.PlumeCpgGenerator$.createCpgForJava(PlumeCpgGenerator.scala:18)
	at io.shiftleft.joern.JoernParse$.generateCpg(JoernParse.scala:25)
	at io.shiftleft.joern.JoernParse$.$anonfun$new$1(JoernParse.scala:12)
	at io.shiftleft.joern.JoernParse$.$anonfun$new$1$adapted(JoernParse.scala:10)
	at scala.Option.foreach(Option.scala:437)
	at io.shiftleft.joern.JoernParse$.delayedEndpoint$io$shiftleft$joern$JoernParse$1(JoernParse.scala:10)
	at io.shiftleft.joern.JoernParse$delayedInit$body.apply(JoernParse.scala:7)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at io.shiftleft.joern.JoernParse$.main(JoernParse.scala:7)
	at io.shiftleft.joern.JoernParse.main(JoernParse.scala)
```

**Comment by DavidBakerEffendi** [comment]
I see this doesn't happen in Plume v0.1.8 so I'll make a pull request to Joern to upgrade
